function SalesView({ sales, search, setSearch, onAdd }: { sales: Sale[]; search: string; setSearch: (v: string) => void; onAdd: () => void }) { const filtered = sales.filter((s) => [s.seller, s.supervisor, s.team].join(" ").toLowerCase().includes(search.toLowerCase())); return <section className="panel full-panel"><div className="panel-head"><div><span className="panel-kicker">OPERAÇÃO COMERCIAL</span><h3>Histórico de vendas</h3></div><button className="primary-btn" onClick={onAdd}><Plus size={16} /> Nova venda</button></div><div className="filters"><div className="search"><Search size={17} /><input placeholder="Buscar vendedor, equipe..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><button className="filter-btn"><Filter size={15} /> Filtros <span>3</span></button><button className="filter-btn">Status <ChevronDown size={14} /></button><button className="filter-btn">Período <ChevronDown size={14} /></button></div><DataTable sales={filtered} /></section>; }

function DataTable({ sales }: { sales: Sale[] }) { return <div className="table-wrap"><table><thead><tr><th>VENDEDOR</th><th>SUPERVISOR</th><th>EQUIPE</th><th>DATA / HORA</th><th>VALOR</th><th>STATUS</th><th /></tr></thead><tbody>{sales.map((s) => <tr key={s.id}><td><div className="person-cell"><div className="avatar small">{initials(s.seller)}</div><strong>{s.seller}</strong></div></td><td>{s.supervisor}</td><td><span className="team-pill">{s.team}</span></td><td>{new Date(`${s.date}T${s.time}`).toLocaleDateString("pt-BR")} <small>{s.time}</small></td><td className="table-value">{money(s.value)}</td><td><span className={`status ${s.status === "Confirmada" ? "confirmed" : "pending"}`}><i />{s.status}</span></td><td><button className="row-more"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table></div>; }

function RankingView({sales}:{sales:Sale[]}) {
  const [type,setType]=useState("Vendedores"); const [metric,setMetric]=useState<"Valor"|"Quantidade">("Valor"); const [days,setDays]=useState(30);
  const cutoff=new Date(); cutoff.setDate(cutoff.getDate()-(days-1));
  const scoped=sales.filter(s=>new Date(s.date+"T00:00:00")>=cutoff);
  const raw=type==="Vendedores"?sellerRanking(scoped):type==="Supervisores"?hierarchyRanking(scoped,"supervisor"):type==="Representantes"?hierarchyRanking(scoped,"representative"):hierarchyRanking(scoped,"master");
  const data=raw.map((x:any)=>({...x,score:metric==="Valor"?x.value:x.sales||scoped.filter(s=>s[type==="Supervisores"?"supervisor":type==="Representantes"?"representative":"master"]===x.name).length})).sort((x:any,y:any)=>y.score-x.score);
  return <section className="panel full-panel"><div className="ranking-hero"><div><span className="panel-kicker">PERFORMANCE</span><h3>Ranking de performance</h3><p>Atualizado automaticamente conforme novas vendas.</p></div><Trophy size={42}/></div>
    <div className="rank-tabs">{["Vendedores","Supervisores","Representantes","Masters"].map(x=><button className={type===x?"active":""} key={x} onClick={()=>setType(x)}>{x}</button>)}</div>
    <div className="rank-tabs"><button className={metric==="Valor"?"active":""} onClick={()=>setMetric("Valor")}>Por valor vendido</button><button className={metric==="Quantidade"?"active":""} onClick={()=>setMetric("Quantidade")}>Por quantidade</button><button className={days===1?"active":""} onClick={()=>setDays(1)}>Hoje</button><button className={days===7?"active":""} onClick={()=>setDays(7)}>7 dias</button><button className={days===30?"active":""} onClick={()=>setDays(30)}>30 dias</button></div>
    <div className="leaderboard">{data.map((item:any,i:number)=>{const max=Math.max(...data.map((x:any)=>x.score),1);return <div className="leader-row" key={item.name}><div className={`leader-place place-${i+1}`}>{i+1}</div><div className="avatar">{initials(item.name)}</div><div className="leader-person"><strong>{item.name}</strong><span>{item.sales?item.sales+" vendas":"Estrutura comercial"}</span></div><div className="leader-bar"><i style={{width:`${Math.max(8,item.score/max*100)}%`}}/></div><strong className="leader-money">{metric==="Valor"?money(item.score):`${item.score} vendas`}</strong></div>})}</div>
  </section>;
}
function hierarchyRanking(sales: Sale[], key: keyof Sale) { const map = new Map<string, { name: string; value: number }>(); sales.forEach((s) => { const name = String(s[key]); const old = map.get(name) || { name, value: 0 }; old.value += s.value; map.set(name, old); }); return [...map.values()].sort((a, b) => b.value - a.value); }

function GoalsView({total,goals,onAdd}:{total:number;goals:Goal[];onAdd:()=>void}) {
  const computed=goals.map(g=>({...g,value:g.name==="Meta geral da operação"?total:g.name==="Time Alpha"?Math.max(g.value,0):g.value}));
  return <section><div className="top-toolbar"><div><span className="panel-kicker">OBJETIVOS</span><h3>Metas individuais e de equipe</h3></div><button className="primary-btn" onClick={onAdd}><Plus size={16}/> Criar meta</button></div><div className="goal-grid">{computed.map(g=>{const p=Math.min(100,Math.round(g.value/g.target*100));return <div className="panel goal-card" key={g.id}><div className="goal-card-head"><div className="metric-icon"><Target size={18}/></div><span className="goal-tag">{g.scope}</span></div><span>{g.name}</span><strong>{money(g.value)}</strong><div className="bar large"><i style={{width:`${p}%`}}/></div><div className="goal-foot"><span>{p}% atingido</span><b>Meta {money(g.target)}</b></div><p>{p>=100?"Meta alcançada!":`Faltam ${money(Math.max(0,g.target-g.value))}`}</p></div>})}<div className="panel create-goal"><div className="create-icon"><Plus size={24}/></div><h3>Nova meta</h3><p>Cadastre uma meta individual ou de equipe.</p><button className="primary-btn" onClick={onAdd}>Configurar meta</button></div></div></section>;
}
function TeamView({sales,users,role,onAdd,onToggle}:{sales:Sale[];users:AppUser[];role:Role;onAdd:()=>void;onToggle:(id:number)=>void}) {
  const allowed=users.filter(u=>role==="Director"||u.role!=="Director");
  return <section className="panel full-panel"><div className="panel-head"><div><span className="panel-kicker">HIERARQUIA</span><h3>Equipe, usuários e permissões</h3><p className="subhead">Hierarquia: Director → Master → Representative → Supervisor → Seller</p></div><button className="primary-btn" onClick={onAdd}><UserPlus size={16}/> Adicionar usuário</button></div><div className="role-cards">{[["Director","Acesso total","Toda a operação"],["Master","Gestão","Representantes + estrutura"],["Representative","Operação","Supervisores + vendedores"],["Supervisor","Equipe","Vendedores"],["Seller","Individual","Próprios resultados"]].map(r=><div className="role-card" key={r[0]}><ShieldCheck size={18}/><strong>{r[0]}</strong><span>{r[1]}</span><small>{r[2]}</small></div>)}</div><div className="table-wrap"><table><thead><tr><th>COLABORADOR</th><th>PERFIL</th><th>MASTER</th><th>REPRESENTANTE</th><th>SUPERVISOR</th><th>EQUIPE</th><th>ACESSO</th></tr></thead><tbody>{allowed.map(u=><tr key={u.id}><td><div className="person-cell"><div className="avatar small">{initials(u.name)}</div><strong>{u.name}</strong></div></td><td>{u.role}</td><td>{u.master||"—"}</td><td>{u.representative||"—"}</td><td>{u.supervisor||"—"}</td><td><span className="team-pill">{u.team||"—"}</span></td><td><button className="access-tag" onClick={()=>onToggle(u.id)}><Check size={13}/>{u.active?"Ativo":"Inativo"}</button></td></tr>)}</tbody></table></div></section>;
}
function DataTeam({ people }: { people: { name: string; supervisor: string; value: number }[] }) { return <div className="table-wrap"><table><thead><tr><th>COLABORADOR</th><th>PERFIL</th><th>SUPERVISOR</th><th>RESULTADO</th><th>META</th><th>ACESSO</th></tr></thead><tbody>{people.map((p, i) => <tr key={p.name}><td><div className="person-cell"><div className="avatar small">{initials(p.name)}</div><strong>{p.name}</strong></div></td><td>Seller</td><td>{p.supervisor}</td><td className="table-value">{money(p.value)}</td><td><span className="goal-tag">{Math.min(100, Math.round((p.value / 30000) * 100))}%</span></td><td><span className="access-tag"><Check size={13} /> Ativo</span></td></tr>)}</tbody></table></div>; }

function ReportsView({sales}:{sales:Sale[]}) {
  const [q,setQ]=useState(""); const [status,setStatus]=useState("Todos"); const [team,setTeam]=useState("Todas"); const [master,setMaster]=useState("Todos"); const [rep,setRep]=useState("Todos"); const [sup,setSup]=useState("Todos"); const [seller,setSeller]=useState("Todos"); const [from,setFrom]=useState(""); const [to,setTo]=useState("");
  const filtered=sales.filter(s=>{const d=s.date;return (!q||[s.seller,s.supervisor,s.representative,s.master,s.team].join(" ").toLowerCase().includes(q.toLowerCase()))&&(status==="Todos"||s.status===status)&&(team==="Todas"||s.team===team)&&(master==="Todos"||s.master===master)&&(rep==="Todos"||s.representative===rep)&&(sup==="Todos"||s.supervisor===sup)&&(seller==="Todos"||s.seller===seller)&&(!from||d>=from)&&(!to||d<=to)});
  const exportCsv=()=>{const rows=[["Vendedor","Supervisor","Representante","Master","Equipe","Data","Hora","Valor","Status"],...filtered.map(s=>[s.seller,s.supervisor,s.representative,s.master,s.team,s.date,s.time,String(s.value),s.status])];const csv=rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob(["\\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="dabliu-relatorio.csv";a.click();URL.revokeObjectURL(a.href);toast.success("Relatório exportado para Excel");};
  const total=filtered.reduce((a,b)=>a+b.value,0);
  return <section className="panel full-panel"><div className="panel-head"><div><span className="panel-kicker">RELATÓRIOS</span><h3>Histórico completo de vendas</h3><p className="subhead">{filtered.length} registros após filtros</p></div><div className="export-actions"><button className="outline-btn" onClick={exportCsv}><FileSpreadsheet size={16}/> Excel</button><button className="outline-btn" onClick={()=>window.print()}><Download size={16}/> PDF</button></div></div>
  <div className="report-filters"><div><label>Busca</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar..."/></div><div><label>Data inicial</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label>Data final</label><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div><label>Status</label><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option><option>Confirmada</option><option>Pendente</option></select></div><div><label>Master</label><select value={master} onChange={e=>setMaster(e.target.value)}><option>Todos</option>{masters.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Representante</label><select value={rep} onChange={e=>setRep(e.target.value)}><option>Todos</option>{representatives.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Supervisor</label><select value={sup} onChange={e=>setSup(e.target.value)}><option>Todos</option>{supervisors.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Vendedor</label><select value={seller} onChange={e=>setSeller(e.target.value)}><option>Todos</option>{sellers.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Equipe</label><select value={team} onChange={e=>setTeam(e.target.value)}><option>Todas</option><option>Time Alpha</option><option>Time Beta</option><option>Time Gamma</option></select></div></div>
  <div className="report-summary"><div><span>Total vendido</span><strong>{money(total)}</strong></div><div><span>Vendas</span><strong>{filtered.length}</strong></div><div><span>Ticket médio</span><strong>{money(filtered.length?total/filtered.length:0)}</strong></div><div><span>Confirmadas</span><strong>{filtered.filter(s=>s.status==="Confirmada").length}</strong></div></div><DataTable sales={filtered}/></section>;
}
function SaleModal({onClose,onSave}:{onClose:()=>void;onSave:(s:Sale)=>void}) {
  const [seller,setSeller]=useState(sellers[0]); const [supervisor,setSupervisor]=useState(supervisors[0]); const [representative,setRepresentative]=useState(representatives[0]); const [master,setMaster]=useState(masters[0]); const [team,setTeam]=useState("Time Alpha"); const [value,setValue]=useState(10000); const [status,setStatus]=useState<Sale["status"]>("Confirmada");
  const submit=(e:React.FormEvent)=>{e.preventDefault();const now=new Date();onSave({id:Date.now(),seller,supervisor,representative,master,team,value:Number(value),date:now.toISOString().slice(0,10),time:now.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),status});};
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="sale-modal" onSubmit={submit}><div className="modal-head"><div><span className="panel-kicker">NOVA OPERAÇÃO</span><h3>Registrar venda</h3><p>Data e hora são preenchidas automaticamente.</p></div><button type="button" onClick={onClose}><X size={19}/></button></div><div className="form-grid"><label>Vendedor<select value={seller} onChange={e=>setSeller(e.target.value)}>{sellers.map(x=><option key={x}>{x}</option>)}</select></label><label>Supervisor<select value={supervisor} onChange={e=>setSupervisor(e.target.value)}>{supervisors.map(x=><option key={x}>{x}</option>)}</select></label><label>Representante<select value={representative} onChange={e=>setRepresentative(e.target.value)}>{representatives.map(x=><option key={x}>{x}</option>)}</select></label><label>Master<select value={master} onChange={e=>setMaster(e.target.value)}>{masters.map(x=><option key={x}>{x}</option>)}</select></label><label>Equipe<select value={team} onChange={e=>setTeam(e.target.value)}><option>Time Alpha</option><option>Time Beta</option><option>Time Gamma</option></select></label><label>Valor<input type="number" min="1" step="0.01" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as Sale["status"])}><option>Confirmada</option><option>Pendente</option></select></label></div><div className="modal-note"><Zap size={17}/><span><strong>Tempo real ativado.</strong> A venda será sincronizada com outras abas abertas.</span></div><div className="modal-actions"><button type="button" className="outline-btn" onClick={onClose}>Cancelar</button><button className="primary-btn"><Check size={16}/> Confirmar venda</button></div></form></div>;
}
function UserModal({onClose,onSave}:{onClose:()=>void;onSave:(u:AppUser)=>void}) {
  const [name,setName]=useState(""); const [role,setRole]=useState<Role>("Seller"); const [team,setTeam]=useState("Time Alpha"); const [supervisor,setSupervisor]=useState("Carlos Lima"); const [representative,setRepresentative]=useState("Marina Costa"); const [master,setMaster]=useState("Rafael Alves");
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()){toast.error("Informe o nome");return}onSave({id:Date.now(),name:name.trim(),role,team:role==="Seller"?team:"",supervisor:role==="Seller"||role==="Supervisor"?supervisor:"",representative:role==="Seller"||role==="Supervisor"||role==="Representative"?representative:"",master:role==="Director"?"":master,active:true})};
  return <div className="modal-backdrop"><form className="sale-modal" onSubmit={submit}><div className="modal-head"><div><span className="panel-kicker">GESTÃO DE ACESSOS</span><h3>Novo usuário</h3></div><button type="button" onClick={onClose}><X size={19}/></button></div><div className="form-grid"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo"/></label><label>Perfil<select value={role} onChange={e=>setRole(e.target.value as Role)}>{["Director","Master","Representative","Supervisor","Seller"].map(x=><option key={x}>{x}</option>)}</select></label><label>Master<select value={master} onChange={e=>setMaster(e.target.value)}><option>Rafael Alves</option></select></label><label>Representante<select value={representative} onChange={e=>setRepresentative(e.target.value)}><option>Marina Costa</option><option>Pedro Mendes</option></select></label><label>Supervisor<select value={supervisor} onChange={e=>setSupervisor(e.target.value)}><option>Carlos Lima</option><option>Juliana Alves</option></select></label><label>Equipe<select value={team} onChange={e=>setTeam(e.target.value)}><option>Time Alpha</option><option>Time Beta</option><option>Time Gamma</option></select></label></div><div className="modal-actions"><button type="button" className="outline-btn" onClick={onClose}>Cancelar</button><button className="primary-btn"><UserPlus size={16}/> Criar usuário</button></div></form></div>;
}
function GoalModal({onClose,onSave}:{onClose:()=>void;onSave:(g:Goal)=>void}) {
  const [name,setName]=useState("");const [target,setTarget]=useState(50000);const [scope,setScope]=useState<Goal["scope"]>("Equipe");const [owner,setOwner]=useState("Time Alpha");
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||target<=0){toast.error("Preencha nome e valor da meta");return}onSave({id:Date.now(),name:name.trim(),target:Number(target),value:0,scope,owner})};
  return <div className="modal-backdrop"><form className="sale-modal" onSubmit={submit}><div className="modal-head"><div><span className="panel-kicker">OBJETIVOS</span><h3>Criar meta</h3></div><button type="button" onClick={onClose}><X size={19}/></button></div><div className="form-grid"><label>Nome da meta<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Meta Time Alpha"/></label><label>Valor alvo<input type="number" min="1" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label>Tipo<select value={scope} onChange={e=>setScope(e.target.value as Goal["scope"])}><option>Equipe</option><option>Individual</option></select></label><label>Responsável<select value={owner} onChange={e=>setOwner(e.target.value)}><option>Time Alpha</option><option>Time Beta</option><option>Time Gamma</option><option>Ana Martins</option></select></label></div><div className="modal-actions"><button type="button" className="outline-btn" onClick={onClose}>Cancelar</button><button className="primary-btn"><Target size={16}/> Criar meta</button></div></form></div>;
}
function TvPanel({ sales, onExit }: { sales: Sale[]; onExit: () => void }) { const [clock, setClock] = useState(new Date()); useEffect(() => { const id = setInterval(() => setClock(new Date()), 1000); return () => clearInterval(id); }, []); const [active, setActive] = useState(0); useEffect(() => { const id = setInterval(() => setActive((x) => (x + 1) % Math.max(1, sales.length)), 6500); return () => clearInterval(id); }, [sales.length]); const sale = sales[active] || sales[0]; return <div className="tv-screen"><div className="tv-top"><div className="tv-brand"><div className="tv-logo">D</div><div><strong>DÁBLIU</strong><span>CENTRAL DE RESULTADOS</span></div></div><div className="tv-clock"><span>OPERAÇÃO AO VIVO</span><strong>{clock.toLocaleTimeString("pt-BR")}</strong></div><button onClick={onExit}>Sair da TV <X size={16} /></button></div><div className="airport-board"><div className="board-title"><span>ÚLTIMAS OPERAÇÕES</span><span><i /> LIVE • ATUALIZAÇÃO AUTOMÁTICA</span></div><div className="board-head"><span>HORA</span><span>VENDEDOR</span><span>SUPERVISOR</span><span>EQUIPE</span><span>VALOR</span><span>STATUS</span></div>{sales.slice(0, 7).map((s, i) => <div className={`board-row ${i === active ? "highlight" : ""}`} key={s.id}><strong>{s.time}</strong><span className="board-person"><b>{initials(s.seller)}</b>{s.seller}</span><span>{s.supervisor}</span><span>{s.team}</span><strong className="board-money">{money(s.value)}</strong><span className="board-status"><i /> CONFIRMADA</span></div>)}</div><div className="tv-bottom"><div><span>VENDAS HOJE</span><strong>{sales.filter((s) => s.date === "2026-09-17").length}</strong></div><div><span>RESULTADO HOJE</span><strong>{money(sales.filter((s) => s.date === "2026-09-17").reduce((a, b) => a + b.value, 0))}</strong></div><div><span>META MENSAL</span><strong>47%</strong></div><div className="tv-message"><Zap size={18} /><span>Nova venda aparece aqui automaticamente</span></div></div></div>; }
function SalesView({sales,search,setSearch,onAdd}:{sales:Sale[];search:string;setSearch:(v:string)=>void;onAdd:()=>void}) {
  const [status,setStatus]=useState("Todos"); const [team,setTeam]=useState("Todas");
  const filtered=sales.filter(s=>([s.seller,s.supervisor,s.representative,s.master,s.team].join(" ").toLowerCase().includes(search.toLowerCase()))&&(status==="Todos"||s.status===status)&&(team==="Todas"||s.team===team));
  return <section className="panel full-panel"><div className="panel-head"><div><span className="panel-kicker">OPERAÇÃO COMERCIAL</span><h3>Histórico de vendas</h3><p className="subhead">{filtered.length} registros encontrados</p></div><button className="primary-btn" onClick={onAdd}><Plus size={16}/> Nova venda</button></div><div className="filters"><div className="search"><Search size={17}/><input placeholder="Buscar vendedor, supervisor, equipe..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="filter-btn" value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option><option>Confirmada</option><option>Pendente</option></select><select className="filter-btn" value={team} onChange={e=>setTeam(e.target.value)}><option>Todas</option><option>Time Alpha</option><option>Time Beta</option><option>Time Gamma</option></select></div><DataTable sales={filtered}/></section>;
}
function DataTable({ sales }: { sales: Sale[] }) { return <div className="table-wrap"><table><thead><tr><th>VENDEDOR</th><th>SUPERVISOR</th><th>EQUIPE</th><th>DATA / HORA</th><th>VALOR</th><th>STATUS</th><th /></tr></thead><tbody>{sales.map((s) => <tr key={s.id}><td><div className="person-cell"><div className="avatar small">{initials(s.seller)}</div><strong>{s.seller}</strong></div></td><td>{s.supervisor}</td><td><span className="team-pill">{s.team}</span></td><td>{new Date(`${s.date}T${s.time}`).toLocaleDateString("pt-BR")} <small>{s.time}</small></td><td className="table-value">{money(s.value)}</td><td><span className={`status ${s.status === "Confirmada" ? "confirmed" : "pending"}`}><i />{s.status}</span></td><td><button className="row-more"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table></div>; }

function RankingView({ sales }: { sales: Sale[] }) { const [type, setType] = useState("Vendedores"); const data = type === "Vendedores" ? sellerRanking(sales) : type === "Supervisores" ? hierarchyRanking(sales, "supervisor") : type === "Representantes" ? hierarchyRanking(sales, "representative") : hierarchyRanking(sales, "master"); return <section className="panel full-panel"><div className="ranking-hero"><div><span className="panel-kicker">PERFORMANCE</span><h3>Quem está entregando resultado</h3><p>Ranking atualizado automaticamente a cada nova venda.</p></div><Trophy size={42} /></div><div className="rank-tabs">{["Vendedores", "Supervisores", "Representantes", "Masters"].map((x) => <button className={type === x ? "active" : ""} key={x} onClick={() => setType(x)}>{x}</button>)}</div><div className="leaderboard">{data.map((item, i) => <div className="leader-row" key={item.name}><div className={`leader-place place-${i + 1}`}>{i + 1}</div><div className="avatar">{initials(item.name)}</div><div className="leader-person"><strong>{item.name}</strong><span>{"sales" in item ? `${item.sales} vendas` : "Estrutura comercial"}</span></div><div className="leader-bar"><i style={{ width: `${Math.max(12, (item.value / data[0].value) * 100)}%` }} /></div><strong className="leader-money">{money(item.value)}</strong><span className="trend"><ArrowUpRight size={14} /> {i === 0 ? "24,8%" : `${18 - i * 3},2%`}</span></div>)}</div></section>; }
function hierarchyRanking(sales: Sale[], key: keyof Sale) { const map = new Map<string, { name: string; value: number }>(); sales.forEach((s) => { const name = String(s[key]); const old = map.get(name) || { name, value: 0 }; old.value += s.value; map.set(name, old); }); return [...map.values()].sort((a, b) => b.value - a.value); }

function GoalsView({ total }: { total: number }) { const goals = [{ name: "Meta geral da operação", target: 240000, value: total }, { name: "Time Alpha", target: 125000, value: 108400 }, { name: "Time Beta", target: 110000, value: 89400 }, { name: "Vendedores", target: 240000, value: total }]; return <section className="goal-grid">{goals.map((g) => { const p = Math.min(100, Math.round((g.value / g.target) * 100)); return <div className="panel goal-card" key={g.name}><div className="goal-card-head"><div className="metric-icon"><Target size={18} /></div><button><MoreHorizontal size={17} /></button></div><span>{g.name}</span><strong>{money(g.value)}</strong><div className="bar large"><i style={{ width: `${p}%` }} /></div><div className="goal-foot"><span>{p}% atingido</span><b>Meta {money(g.target)}</b></div><p>{p >= 100 ? "Meta alcançada! Excelente resultado." : `Faltam ${money(g.target - g.value)} para alcançar.`}</p></div>; })}<div className="panel create-goal"><div className="create-icon"><Plus size={24} /></div><h3>Criar nova meta</h3><p>Defina objetivos individuais ou por equipe e acompanhe a evolução.</p><button className="primary-btn" onClick={() => toast.success("Meta preparada", { description: "A configuração será aberta na próxima etapa." })}>Configurar meta</button></div></section>; }

function TeamView({ sales, role }: { sales: Sale[]; role: Role }) { const people = sellers.map((name) => ({ name, supervisor: sales.find((s) => s.seller === name)?.supervisor || "Carlos Lima", value: sales.filter((s) => s.seller === name).reduce((a, b) => a + b.value, 0) })); return <section className="panel full-panel"><div className="panel-head"><div><span className="panel-kicker">HIERARQUIA</span><h3>Equipe e acessos</h3><p className="subhead">Visão permitida para <strong>{role}</strong> • Director tem acesso total.</p></div><button className="primary-btn" onClick={() => toast.success("Novo usuário", { description: "Formulário de criação preparado." })}><UserPlus size={16} /> Adicionar usuário</button></div><div className="role-cards">{([["Director", "Acesso total", "Tudo"], ["Master", "Gestão", "Representatives + estrutura"], ["Representative", "Operação", "Supervisores + sellers"], ["Supervisor", "Equipe", "Sellers"], ["Seller", "Individual", "Próprios resultados"]] as string[][]).map((r) => <div className="role-card" key={r[0]}><ShieldCheck size={18} /><strong>{r[0]}</strong><span>{r[1]}</span><small>{r[2]}</small></div>)}</div><DataTeam people={people} /></section>; }
function DataTeam({ people }: { people: { name: string; supervisor: string; value: number }[] }) { return <div className="table-wrap"><table><thead><tr><th>COLABORADOR</th><th>PERFIL</th><th>SUPERVISOR</th><th>RESULTADO</th><th>META</th><th>ACESSO</th></tr></thead><tbody>{people.map((p, i) => <tr key={p.name}><td><div className="person-cell"><div className="avatar small">{initials(p.name)}</div><strong>{p.name}</strong></div></td><td>Seller</td><td>{p.supervisor}</td><td className="table-value">{money(p.value)}</td><td><span className="goal-tag">{Math.min(100, Math.round((p.value / 30000) * 100))}%</span></td><td><span className="access-tag"><Check size={13} /> Ativo</span></td></tr>)}</tbody></table></div>; }

function ReportsView({ sales }: { sales: Sale[] }) { const exportCsv = () => { const csv = ["Vendedor;Supervisor;Representante;Master;Equipe;Data;Hora;Valor;Status", ...sales.map((s) => `${s.seller};${s.supervisor};${s.representative};${s.master};${s.team};${s.date};${s.time};${s.value};${s.status}`)].join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "dabliu-relatorio.csv"; a.click(); URL.revokeObjectURL(a.href); toast.success("Relatório exportado", { description: "Arquivo CSV compatível com Excel." }); }; return <section className="report-grid"><div className="panel full-panel"><div className="panel-head"><div><span className="panel-kicker">RELATÓRIOS</span><h3>Performance comercial</h3></div><div className="export-actions"><button className="outline-btn" onClick={exportCsv}><FileSpreadsheet size={16} /> Excel</button><button className="outline-btn" onClick={() => window.print()}><Download size={16} /> PDF</button></div></div><div className="report-filters"><div><label>Período</label><button>01/09/2026 — 17/09/2026 <CalendarDays size={15} /></button></div><div><label>Master</label><button>Todos <ChevronDown size={15} /></button></div><div><label>Representante</label><button>Todos <ChevronDown size={15} /></button></div><div><label>Supervisor</label><button>Todos <ChevronDown size={15} /></button></div></div><div className="report-summary"><div><span>Total vendido</span><strong>{money(sales.reduce((a, b) => a + b.value, 0))}</strong></div><div><span>Vendas</span><strong>{sales.length}</strong></div><div><span>Ticket médio</span><strong>{money(sales.reduce((a, b) => a + b.value, 0) / sales.length)}</strong></div><div><span>Confirmadas</span><strong>{sales.filter((s) => s.status === "Confirmada").length}</strong></div></div><DataTable sales={sales} /></div></section>; }

function SaleModal({ onClose, onSave }: { onClose: () => void; onSave: (s: Sale) => void }) { const [seller, setSeller] = useState(sellers[0]); const [supervisor, setSupervisor] = useState(supervisors[0]); const [value, setValue] = useState(10000); const [team, setTeam] = useState("Time Alpha"); const submit = (e: React.FormEvent) => { e.preventDefault(); const now = new Date(); onSave({ id: Date.now(), seller, supervisor, representative: representatives[0], master: masters[0], team, value: Number(value), date: "2026-09-17", time: now.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }), status: "Confirmada" }); }; return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="sale-modal" onSubmit={submit}><div className="modal-head"><div><span className="panel-kicker">NOVA OPERAÇÃO</span><h3>Registrar venda</h3><p>A venda aparecerá automaticamente na Central TV.</p></div><button type="button" onClick={onClose}><X size={19} /></button></div><div className="form-grid"><label>Vendedor<select value={seller} onChange={(e) => setSeller(e.target.value)}>{sellers.map((x) => <option key={x}>{x}</option>)}</select></label><label>Supervisor<select value={supervisor} onChange={(e) => setSupervisor(e.target.value)}>{supervisors.map((x) => <option key={x}>{x}</option>)}</select></label><label>Equipe<select value={team} onChange={(e) => setTeam(e.target.value)}><option>Time Alpha</option><option>Time Beta</option><option>Time Gamma</option></select></label><label>Valor da venda<input type="number" min="1" value={value} onChange={(e) => setValue(Number(e.target.value))} /></label></div><div className="modal-note"><Zap size={17} /><span><strong>Tempo real ativado.</strong> Esta operação sincroniza com outras telas abertas do Dábliu.</span></div><div className="modal-actions"><button type="button" className="outline-btn" onClick={onClose}>Cancelar</button><button className="primary-btn"><Check size={16} /> Confirmar venda</button></div></form></div>; }

function TvPanel({ sales, onExit }: { sales: Sale[]; onExit: () => void }) { const [clock, setClock] = useState(new Date()); useEffect(() => { const id = setInterval(() => setClock(new Date()), 1000); return () => clearInterval(id); }, []); const [active, setActive] = useState(0); useEffect(() => { const id = setInterval(() => setActive((x) => (x + 1) % Math.max(1, sales.length)), 6500); return () => clearInterval(id); }, [sales.length]); const sale = sales[active] || sales[0]; return <div className="tv-screen"><div className="tv-top"><div className="tv-brand"><div className="tv-logo">D</div><div><strong>DÁBLIU</strong><span>CENTRAL DE RESULTADOS</span></div></div><div className="tv-clock"><span>OPERAÇÃO AO VIVO</span><strong>{clock.toLocaleTimeString("pt-BR")}</strong></div><button onClick={onExit}>Sair da TV <X size={16} /></button></div><div className="airport-board"><div className="board-title"><span>ÚLTIMAS OPERAÇÕES</span><span><i /> LIVE • ATUALIZAÇÃO AUTOMÁTICA</span></div><div className="board-head"><span>HORA</span><span>VENDEDOR</span><span>SUPERVISOR</span><span>EQUIPE</span><span>VALOR</span><span>STATUS</span></div>{sales.slice(0, 7).map((s, i) => <div className={`board-row ${i === active ? "highlight" : ""}`} key={s.id}><strong>{s.time}</strong><span className="board-person"><b>{initials(s.seller)}</b>{s.seller}</span><span>{s.supervisor}</span><span>{s.team}</span><strong className="board-money">{money(s.value)}</strong><span className="board-status"><i /> CONFIRMADA</span></div>)}</div><div className="tv-bottom"><div><span>VENDAS HOJE</span><strong>{sales.filter((s) => s.date === "2026-09-17").length}</strong></div><div><span>RESULTADO HOJE</span><strong>{money(sales.filter((s) => s.date === "2026-09-17").reduce((a, b) => a + b.value, 0))}</strong></div><div><span>META MENSAL</span><strong>47%</strong></div><div className="tv-message"><Zap size={18} /><span>Nova venda aparece aqui automaticamente</span></div></div></div>; }
