// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wenvtbkseledfnbfubir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlbnZ0YmtzZWxlZGZuYmZ1YmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxODk0MDksImV4cCI6MjEwNTc2NTQwOX0.l95rYDs4NyHH7x3Z4RVUqx-bJFAEsU8mrQHNfqNn3pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});